# WD MyCloud package builder CI
# by Stefaan Ghysels

name: WD MyCloud package CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: wdpk/wdpk
      options: -v ${{github.workspace}}/packages:/github/workspace/packages
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get packages that were changed in the last commit
        id: diff
        run: |
          pkgs=$(git diff-tree --name-only --no-commit-id -r HEAD | grep ^wdpk)
          echo ::set-output name=pkgs::"${pkgs}"

      - name: Get platforms
        id: platforms
        run: echo ::set-output name=arr::"WDMyCloudEX4100-EX4100 WDMyCloudDL4100-DL4100 WDMyCloudEX2100-EX2100 WDMyCloudDL2100-DL2100 WDMyCloudMirror-MirrorG2 MyCloudEX2Ultra-EX2Ultra MyCloudPR4100-PR4100 MyCloudPR2100-PR2100"

      - name: Make APKG packages for selected platforms
        id: make_apkg
        env:
          PLATFORMS: ${{ steps.platforms.outputs.arr }}
          PACKAGES: ${{ steps.diff.outputs.pkgs }}
        run: |

          pkg=$(echo ${PACKAGES} | cut -d/ -f2)
          echo ::set-output name=pkg::"$pkg"
          cd wdpk/${pkg}
          DATE="$(date +"%m%d%Y")"
          CWD="$(pwd)"
          VERSION="$(awk '/Version/{print $NF}' apkg.rc)"
          echo ::set-output name=version::"$VERSION"
          NAME="$(awk '/AddonShowName/{print $NF}' apkg.rc)"
          echo ::set-output name=name::"$NAME"

          echo "Building ${pkg} version ${VERSION}"
          echo "$(ls -l ../..)"
          RELEASE_DIR="../../packages/${pkg}/OS5"
          mkdir -p "${RELEASE_DIR}"

          echo PLF $PLATFORMS - $arr - $PACKAGES
          for fullmodel in $PLATFORMS
          do
            model=${fullmodel%-*}
            name=${fullmodel#*-}
            echo "Build ${pkg} for ${platform}"
            ../../mksapkg-OS5 -E -s -m $model > /dev/null
            mv ../${platform}*.bin\(* ../${pkg}_${VERSION}_${name}.bin
          done
          echo "$(ls -l ..)"

      - name: Upload binary packages to Bintray
        uses: masofcon/upload-to-bintray-github-action@master
        with:
          source_path: ./wdpk/${{steps.make_apkg.outputs.pkg}}_${{steps.make_apkg.outputs.version}}_*.bin
          api_user: tfl
          api_key: ${{ secrets.BINTRAY_API_KEY }} # An API key can be obtained from the user profile page.
          repository: wdpksrc
          package: ${{ steps.make_apkg.outputs.name }}
          version: ${{ steps.make_apkg.outputs.version }}
          upload_path: ${{ steps.make_apkg.outputs.pkg }}/OS5
          publish: 1
          override: 0